### ISSUE TITLE
Shouldn't have a space between a variable and unary ++/-- operators

### ISSUE THREAD

**Issue by jacekradko** [tests-always-included/pretty-js#10]
There shouldn't be a space between a variable and the unary ++/-- operators. 

```javascript
i++;
--i;
```
Prints to
```javascript
i ++;
-- i;
```
Here is a failing scenario for this:
```json
{
  "input": "i++; --i;",
  "output": "i++;\n--i;"
}
```

**Comment by jacekradko** [comment]
Alternately, there should be an option to remove those spaces.

**Comment by fidian** [comment]
I'm all for the option.  Any suggestions for the name before I make something up?

**Comment by jacekradko** [comment]
Nope. I defer to your good judgement.

**Comment by fidian** [comment]
Option now exists.  Let me know if the code isn't doing what you'd expect.
